[package]
name = "stable-write-only"
version = "0.1.1"
description = "Manages a write-only stable memory stream"
repository = "https://github.com/skilesare/StableWriteOnly.mo"
keywords = [ "stable", "memory" ]
license = "MIT"

[dependencies]
core = "2.0.0"

[dev-dependencies]
test = "2.1.2"
fuzz = "1.0.0"
matchers = "2.1.0"

[toolchain]
moc = "1.1.0"
